#server.port=7000
#spring.application.name=01-auth-service
#eureka.client.service-url.defaultZone=http://localhost:5000/eureka/
#spring.cloud.loadbalancer.ribbon.enabled=false
#
#spring.datasource.url=jdbc:mysql://119.45.146.109:3307/lhxm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.platform=mysql
#spring.redis.host=119.45.146.109
#
#jwt.header=Authorization
#jwt.secret=mySecret
##token有效期一天
#jwt.expiration=86400
#jwt.tokenHead="Bearer "
#
##mybatis-plus
#mybatis-plus.mapper-locations=classpath:mappers/*/*.xml
#mybatis-plus.type-aliases-package=com.hlso.auth.domain
#mybatis-plus.configuration.map-underscore-to-camel-case=true
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
